### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Calinou** [Kehom/GodotAddonPack#1]
The repository currently doesn't seem to contain any license. Could you add one, please? See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

For reference, most open source Godot add-ons use the MIT license.

**Comment by Kehom** [comment]
Thanks for the heads up (and checking the repository). I did add the license to every single addon file. Thought it would be enough! Anyway, added the license into the repository!

**Comment by Calinou** [comment]
Thanks!
