### ISSUE TITLE
[Network] player_removed is not called for clients

### ISSUE THREAD

**Issue by yuraj11** [Kehom/GodotAddonPack#18]
player_added signal works fine and it's called on all clients but player_removed is called only on server.

**Comment by fairhat** [comment]
@yuraj11 are you using websockets and testing on smartphone browsers?

I noticed that websockets on iOS Safari aren't properl closed if the user leaves the website. Sometimes it takes up to 10 mins for godot to notice that the player has left.

**Comment by yuraj11** [comment]
On desktop but there's implementation but it is commented in network.gd in function _on_player_disconnected for some reason.

**Comment by Kehom** [comment]
Is this still the case? I ask because 6192200976d9f4e8471a60a03cd4c0966d2b731c has changed the `_on_player_disconnected` and there is no commented "command" in it since that commit.

**Comment by yuraj11** [comment]
Yeah sorry didn't see it. Works :)
