### ISSUE TITLE
[Network] Snapshot support for more custom data

### ISSUE THREAD

**Issue by yuraj11** [Kehom/GodotAddonPack#24]
Is it possible to use arrays with SnapEntityBase? I would like to use PoolByteArray to synchronize array of bytes.

**Comment by Kehom** [comment]
Hey, I deliberately didn't add support for array types because I didn't think of a use case in which it would justify. Nevertheless, I'm open to add it if the use case do indeed require this kind of data.

**Comment by yuraj11** [comment]
Example is when player can have effects on him - positive (extra jump, speed...) or negative (poison, slowness...) but dynamic size (because you can obtain them anytime) - it will be array of IDs (possibly bytes to save bandwidth) of every effect type. I have map Id = effect class and I can easily sync all effects between players. Byte array is versatile because you can combine it with your encdec addon and do custom serialization.

**Comment by Kehom** [comment]
Ohhh! For some (borked) reason whenever I thought about character effects I didn't think arrays would be necessary.
Now, thinking about the case I believe `PoolByteArray`, `PoolIntArray` and `PoolRealArray` are possible good new types to be added into the supported list.

The only thing I have to think about is in how to perform the correct calculation of the deltas without completely killing performance while extracting data from the arrays (although I'm probably overthinking things here - again on that "half asleep mode").

**Comment by Kehom** [comment]
Forgot to tag this on commit 3e7d15d9b85f3d8cef8df721be373459500bcac7.
