### ISSUE TITLE
Can the network addon add a solution for serialization and deserialization using protobuf ?

### ISSUE THREAD

**Issue by NPSnuli** [Kehom/GodotAddonPack#45]
Can the network plugin add a solution for serialization and deserialization using protobuf, currently it's directly using Godot's own PoolByteArray right? Maybe protobuf is better for passing large amounts of data.

**Comment by Kehom** [comment]
Well, Godot does not offer support for Protobuf, meaning that pure GDScript might be rather complicated to deal with.

That said, in what sense would it be *better* than byte arrays? And why?
Keep in mind that the network addon takes Variant, strips out "header information" and pack into the byte array only the data.

**Comment by NPSnuli** [comment]
@Kehom I'm just trying to include more options to become a bit more flexible, and if it's indeed a complexity, so be it

**Comment by Kehom** [comment]
Ok. I asked what would make it *better* because implementation difficulty/complexity/cost sometimes is justified by the benefits. I'm not entirely sure in this case.
